/**
 * countries.ts
 *
 * Lista de países con su código ISO2, código telefónico (dial code) y nombre
 * en español. Se usa en el selector de país del campo de teléfono (registro).
 * La bandera se calcula a partir del ISO2 usando indicadores regionales Unicode,
 * así no hay que guardar el emoji de cada país a mano.
 */

export interface Country {
  iso2: string;
  name: string;
  dialCode: string;
}

/** Convierte un código ISO2 (ej. "CR") en su emoji de bandera (🇨🇷). */
export function flagEmoji(iso2: string): string {
  return iso2
    .toUpperCase()
    .split('')
    .map((c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
    .join('');
}

// [iso2, dialCode, nombre en español]
const RAW: [string, string, string][] = [
  ['CR', '506', 'Costa Rica'],
  ['MX', '52', 'México'],
  ['US', '1', 'Estados Unidos'],
  ['CA', '1', 'Canadá'],
  ['GT', '502', 'Guatemala'],
  ['HN', '504', 'Honduras'],
  ['SV', '503', 'El Salvador'],
  ['NI', '505', 'Nicaragua'],
  ['PA', '507', 'Panamá'],
  ['BZ', '501', 'Belice'],
  ['CO', '57', 'Colombia'],
  ['VE', '58', 'Venezuela'],
  ['EC', '593', 'Ecuador'],
  ['PE', '51', 'Perú'],
  ['BO', '591', 'Bolivia'],
  ['CL', '56', 'Chile'],
  ['AR', '54', 'Argentina'],
  ['UY', '598', 'Uruguay'],
  ['PY', '595', 'Paraguay'],
  ['BR', '55', 'Brasil'],
  ['GY', '592', 'Guyana'],
  ['SR', '597', 'Surinam'],
  ['CU', '53', 'Cuba'],
  ['DO', '1', 'República Dominicana'],
  ['HT', '509', 'Haití'],
  ['JM', '1', 'Jamaica'],
  ['TT', '1', 'Trinidad y Tobago'],
  ['BS', '1', 'Bahamas'],
  ['BB', '1', 'Barbados'],
  ['PR', '1', 'Puerto Rico'],
  ['ES', '34', 'España'],
  ['PT', '351', 'Portugal'],
  ['FR', '33', 'Francia'],
  ['DE', '49', 'Alemania'],
  ['IT', '39', 'Italia'],
  ['GB', '44', 'Reino Unido'],
  ['IE', '353', 'Irlanda'],
  ['NL', '31', 'Países Bajos'],
  ['BE', '32', 'Bélgica'],
  ['CH', '41', 'Suiza'],
  ['AT', '43', 'Austria'],
  ['SE', '46', 'Suecia'],
  ['NO', '47', 'Noruega'],
  ['DK', '45', 'Dinamarca'],
  ['FI', '358', 'Finlandia'],
  ['IS', '354', 'Islandia'],
  ['PL', '48', 'Polonia'],
  ['CZ', '420', 'República Checa'],
  ['SK', '421', 'Eslovaquia'],
  ['HU', '36', 'Hungría'],
  ['RO', '40', 'Rumania'],
  ['BG', '359', 'Bulgaria'],
  ['GR', '30', 'Grecia'],
  ['TR', '90', 'Turquía'],
  ['RU', '7', 'Rusia'],
  ['UA', '380', 'Ucrania'],
  ['BY', '375', 'Bielorrusia'],
  ['LT', '370', 'Lituania'],
  ['LV', '371', 'Letonia'],
  ['EE', '372', 'Estonia'],
  ['HR', '385', 'Croacia'],
  ['RS', '381', 'Serbia'],
  ['SI', '386', 'Eslovenia'],
  ['BA', '387', 'Bosnia y Herzegovina'],
  ['AL', '355', 'Albania'],
  ['MT', '356', 'Malta'],
  ['LU', '352', 'Luxemburgo'],
  ['CY', '357', 'Chipre'],
  ['AD', '376', 'Andorra'],
  ['MC', '377', 'Mónaco'],
  ['SM', '378', 'San Marino'],
  ['VA', '379', 'Ciudad del Vaticano'],
  ['LI', '423', 'Liechtenstein'],
  ['MD', '373', 'Moldavia'],
  ['MK', '389', 'Macedonia del Norte'],
  ['ME', '382', 'Montenegro'],
  ['XK', '383', 'Kosovo'],
  ['GE', '995', 'Georgia'],
  ['AM', '374', 'Armenia'],
  ['AZ', '994', 'Azerbaiyán'],
  ['KZ', '7', 'Kazajistán'],
  ['UZ', '998', 'Uzbekistán'],
  ['TM', '993', 'Turkmenistán'],
  ['TJ', '992', 'Tayikistán'],
  ['KG', '996', 'Kirguistán'],
  ['MN', '976', 'Mongolia'],
  ['CN', '86', 'China'],
  ['JP', '81', 'Japón'],
  ['KR', '82', 'Corea del Sur'],
  ['KP', '850', 'Corea del Norte'],
  ['TW', '886', 'Taiwán'],
  ['HK', '852', 'Hong Kong'],
  ['MO', '853', 'Macao'],
  ['IN', '91', 'India'],
  ['PK', '92', 'Pakistán'],
  ['BD', '880', 'Bangladés'],
  ['LK', '94', 'Sri Lanka'],
  ['NP', '977', 'Nepal'],
  ['BT', '975', 'Bután'],
  ['MM', '95', 'Myanmar'],
  ['TH', '66', 'Tailandia'],
  ['LA', '856', 'Laos'],
  ['KH', '855', 'Camboya'],
  ['VN', '84', 'Vietnam'],
  ['MY', '60', 'Malasia'],
  ['SG', '65', 'Singapur'],
  ['ID', '62', 'Indonesia'],
  ['PH', '63', 'Filipinas'],
  ['BN', '673', 'Brunéi'],
  ['TL', '670', 'Timor Oriental'],
  ['AU', '61', 'Australia'],
  ['NZ', '64', 'Nueva Zelanda'],
  ['FJ', '679', 'Fiyi'],
  ['PG', '675', 'Papúa Nueva Guinea'],
  ['SB', '677', 'Islas Salomón'],
  ['VU', '678', 'Vanuatu'],
  ['WS', '685', 'Samoa'],
  ['TO', '676', 'Tonga'],
  ['KI', '686', 'Kiribati'],
  ['FM', '691', 'Micronesia'],
  ['MH', '692', 'Islas Marshall'],
  ['PW', '680', 'Palaos'],
  ['NR', '674', 'Nauru'],
  ['TV', '688', 'Tuvalu'],
  ['SA', '966', 'Arabia Saudita'],
  ['AE', '971', 'Emiratos Árabes Unidos'],
  ['QA', '974', 'Catar'],
  ['KW', '965', 'Kuwait'],
  ['BH', '973', 'Baréin'],
  ['OM', '968', 'Omán'],
  ['YE', '967', 'Yemen'],
  ['IQ', '964', 'Irak'],
  ['IR', '98', 'Irán'],
  ['IL', '972', 'Israel'],
  ['PS', '970', 'Palestina'],
  ['JO', '962', 'Jordania'],
  ['LB', '961', 'Líbano'],
  ['SY', '963', 'Siria'],
  ['AF', '93', 'Afganistán'],
  ['EG', '20', 'Egipto'],
  ['LY', '218', 'Libia'],
  ['TN', '216', 'Túnez'],
  ['DZ', '213', 'Argelia'],
  ['MA', '212', 'Marruecos'],
  ['SD', '249', 'Sudán'],
  ['SS', '211', 'Sudán del Sur'],
  ['ET', '251', 'Etiopía'],
  ['ER', '291', 'Eritrea'],
  ['DJ', '253', 'Yibuti'],
  ['SO', '252', 'Somalia'],
  ['KE', '254', 'Kenia'],
  ['UG', '256', 'Uganda'],
  ['TZ', '255', 'Tanzania'],
  ['RW', '250', 'Ruanda'],
  ['BI', '257', 'Burundi'],
  ['CD', '243', 'R.D. del Congo'],
  ['CG', '242', 'República del Congo'],
  ['CF', '236', 'República Centroafricana'],
  ['CM', '237', 'Camerún'],
  ['TD', '235', 'Chad'],
  ['NE', '227', 'Níger'],
  ['NG', '234', 'Nigeria'],
  ['BJ', '229', 'Benín'],
  ['TG', '228', 'Togo'],
  ['GH', '233', 'Ghana'],
  ['CI', '225', 'Costa de Marfil'],
  ['LR', '231', 'Liberia'],
  ['SL', '232', 'Sierra Leona'],
  ['GN', '224', 'Guinea'],
  ['GW', '245', 'Guinea-Bisáu'],
  ['GQ', '240', 'Guinea Ecuatorial'],
  ['GA', '241', 'Gabón'],
  ['ML', '223', 'Malí'],
  ['BF', '226', 'Burkina Faso'],
  ['SN', '221', 'Senegal'],
  ['MR', '222', 'Mauritania'],
  ['GM', '220', 'Gambia'],
  ['CV', '238', 'Cabo Verde'],
  ['ST', '239', 'Santo Tomé y Príncipe'],
  ['AO', '244', 'Angola'],
  ['ZM', '260', 'Zambia'],
  ['ZW', '263', 'Zimbabue'],
  ['MW', '265', 'Malaui'],
  ['MZ', '258', 'Mozambique'],
  ['NA', '264', 'Namibia'],
  ['BW', '267', 'Botsuana'],
  ['ZA', '27', 'Sudáfrica'],
  ['SZ', '268', 'Esuatini'],
  ['LS', '266', 'Lesoto'],
  ['MG', '261', 'Madagascar'],
  ['MU', '230', 'Mauricio'],
  ['SC', '248', 'Seychelles'],
  ['KM', '269', 'Comoras'],
  ['IS', '354', 'Islandia'],
];

export const COUNTRIES: Country[] = Array.from(
  new Map(
    RAW.map(([iso2, dialCode, name]) => [iso2, { iso2, dialCode, name }])
  ).values()
).sort((a, b) => a.name.localeCompare(b.name, 'es'));

export const DEFAULT_COUNTRY: Country =
  COUNTRIES.find((c) => c.iso2 === 'CR') ?? COUNTRIES[0];
